test_that("LRT statistics and p-values are valid", {
  toy <- read_mrmoss_summary_stats(system.file("extdata", "toy_summary_stats.csv", package = "MRMOSS"))
  R <- read_outcome_correlation(system.file("extdata", "toy_outcome_correlation.csv", package = "MRMOSS"))
  fit <- fit_mrmoss(summary_stats = toy, R = R, maxiter = 500)
  olrt <- outcome_lrt(fit)
  glrt <- global_lrt(fit)
  expect_equal(fit$beta, c(0.15637842, -0.08073786, 0.06622268), tolerance = 1e-5)
  expect_equal(olrt$lrt, c(70.22153, 24.62867, 24.86529), tolerance = 1e-4)
  expect_equal(glrt$lrt, 158.9726, tolerance = 1e-4)
  expect_true(all(olrt$lrt >= 0))
  expect_true(all(olrt$p_value >= 0 & olrt$p_value <= 1))
  expect_true(glrt$lrt >= 0)
  expect_true(glrt$p_value >= 0 & glrt$p_value <= 1)
})

test_that("domain and subset LRT helpers return named rows", {
  toy <- read_mrmoss_summary_stats(system.file("extdata", "toy_summary_stats.csv", package = "MRMOSS"))
  R <- read_outcome_correlation(system.file("extdata", "toy_outcome_correlation.csv", package = "MRMOSS"))
  domains <- system.file("extdata", "toy_domain_map.csv", package = "MRMOSS")
  fit <- fit_mrmoss(summary_stats = toy, R = R, maxiter = 500)
  dlrt <- domain_lrt(fit, domains)
  slrt <- subset_lrt(fit, list(first_two = c("outcome_1", "outcome_2")))
  expect_setequal(dlrt$subset, c("domain_a", "domain_b"))
  expect_equal(slrt$subset, "first_two")
  expect_error(subset_lrt(fit, list(bad = "not_an_outcome")), "match")
  expect_error(subset_lrt(fit, list(bad = 0)), "between 1")
  expect_error(subset_lrt(fit, list()), "non-empty")
  expect_error(subset_lrt(fit, list(first = 1), subset_names = c("a", "b")), "same length")
  expect_error(subset_lrt(fit, list(dup = c(1, 1))), "unique")
  expect_error(subset_lrt(fit, list(first = 1), maxiter = 0), "maxiter")
})
