# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MRMOSS_PX_xprod_joint_cpp <- function(gamma_hat, Gamma_hat, R, n1, n2, theta0, maxiter, rd, tol = 1e-8) {
    .Call(`_MRMOSS_MRMOSS_PX_xprod_joint_cpp`, gamma_hat, Gamma_hat, R, n1, n2, theta0, maxiter, rd, tol)
}

MRMOSS_PX_xprod_lrt_diag_cpp <- function(gamma_hat, Gamma_hat, R, n1, n2, theta0, test, maxiter, rd, tol = 1e-5, miniter = 20L) {
    .Call(`_MRMOSS_MRMOSS_PX_xprod_lrt_diag_cpp`, gamma_hat, Gamma_hat, R, n1, n2, theta0, test, maxiter, rd, tol, miniter)
}

MRMOSS_PX_xprod_subset_lrt_cpp <- function(gamma_hat, Gamma_hat, R, n1, n2, theta0, subsets, subset_names, maxiter, rd, tol = 1e-5, miniter = 20L) {
    .Call(`_MRMOSS_MRMOSS_PX_xprod_subset_lrt_cpp`, gamma_hat, Gamma_hat, R, n1, n2, theta0, subsets, subset_names, maxiter, rd, tol, miniter)
}

